# Build azure functions app using devops

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore build and publish solution'
  inputs:
    command: publish
    arguments: -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
    projects: '**/*.csproj'
- script: ls $(Build.ArtifactStagingDirectory)
  displayName: 'List artifact folder content'