# Build azure functions app using devops
pool: 'Hosted VS2017'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore build and publish solution'
  inputs:
    command: publish
    arguments: -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
    publishWebProjects: false
    zipAfterPublish: true
    projects: '**/*.csproj'
- script: ls $(Build.ArtifactStagingDirectory)
  displayName: 'List artifact folder content'