# Build azure functions app using devops

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore build and publish solution'
  inputs:
    command: publish
    arguments: -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
- task:
    script: ls $(Build.ArtifactStagingDirectory)